baseURL = 'https://test-dr-tom.netlify.app'
relativeURLs = true
languageCode = 'en-us'
title = 'Ordination Dr. Tom Laube - Facharzt für Allgemeinmedizin und Unfallchirurgie'

disableKinds = ["taxonomy", "term"]